title: Todo List Hell
email: kenttokunaga@gmail.com
description: >-
  Personal blog of things I want to learn.
baseurl: ""
url: ""
github_username: kenttoku
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
